name: Deploy to Cloud Run from Source

on:
  push:
    branches: [ "main" ]

env:
  PROJECT_ID: devops_secops_course # TODO: update Google Cloud project id
  SERVICE: taskman-hhn-secops-projectgrp-vrock # TODO: update Cloud Run service name
  REGION: europe-west4 # TODO: update Cloud Run service region

jobs:
  deploy:
    # Add 'id-token' with the intended permissions for workload identity federation
    permissions:
      contents: 'read'
      id-token: 'write'

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v0
        with:
          service: ${{ env.SERVICE }}
          region: ${{ env.REGION }}
          # NOTE: If required, update to the appropriate source folder
          source: ./
        env:
          BACKEND: memory

      - name: Log in to Docker Hub
        uses:  docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v2
        with:
          images: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
            vrock1/hhn-secops-projectgrp-vrock
          flavor: latest=true
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      
      - name: Authentication to Cloud Run
        uses: 'google-github-actions/auth@v1'
        with:
         workload_identity_provider: '${{ secrets.HS_PROVIDER }}'
         service_account: '${{ secrets.HS_SERVICE_ACCOUNT }}'

      - name: Deploy to Cloud Run
        id: 'deploy'
        uses: 'google-github-actions/deploy-cloudrun@v1'
        with:
         service:  ${{ env.SERVICE }}
         image: 'docker.io/vrock1/hhn-secops-projectgrp-vrock:latest'
         env_vars: BACKEND=memory
         region: ${{env.REGION}}

      - name: 'Output'
        run: 'curl "${{ steps.deploy.outputs.url }}"' 